apiVersion: apps/v1  #extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: recipe-app-api
  name: recipe-app-api
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 60
  selector:
    matchLabels:
      app: recipe-app-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recipe-app-api
    spec:
      containers:
      - name: recipe-app-api
        image: harsh2013/recipe-app-api
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8000
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 10
          periodSeconds: 20
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 10
          periodSeconds: 20
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1  #v1
kind: Service
metadata:
  labels: #PODS
    app: recipe-app-api
  name: recipe-app-api
  namespace: default
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 8000 #CHANGE
    protocol: TCP
    targetPort: 8000 #CHANGE
  selector:
    app: recipe-app-api
  sessionAffinity: None #CHANGE
  type: LoadBalancer